### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Aerondightt2** [ARTIRL/LevelingBOT_LOL#3]
Hello i try to use your program. i did all settings for bot. But when its starts a game on the console its said game is not started. how can i fix that

**Comment by Aerondightt2** [comment]
![Uploading resim_2024-09-15_135144990.png…]()

**Comment by Aerondightt2** [comment]
![resim_2024-09-15_135202585](https://github.com/user-attachments/assets/b16de44b-59f5-418f-8990-4143f31b47b7)

**Comment by ARTIRL** [comment]
Greetings @Aerondightt2  i'd like you to give me more inforamtion about your issue so i can assist you.
When the script is done selecting your champion and enters the 5V5 loading screen , is the game on the primary window ? 
If not there is a high chance the script wont detect if the game started .

**Comment by Aerondightt2** [comment]
Hello @ARTIRL i have 1 monitor and im opening on this. My league of legends settings like this,

Client 1024x576. it opens game, search game, enter game, pick champion, and wait for the start. When game stars on the command prompt says game didnt start My league of legends client settings like this 1920x1080 windowed. and character attack set to space key

**Comment by ARTIRL** [comment]
Okay so it seems all settings are alright and the script is working fine . However the error message "Game didn't Start" means that the script is unable to detect an image like this 
![image](https://github.com/user-attachments/assets/633534a9-2488-4592-aada-8bdf1a185999)
The most common reason for this is most likely : the primary window on your desktop isn't the League of Legends Game
What i suggest is : 
Run the script , Close all the windows on your computer (except the script, you can reduce the script window) if you noticed that after you locked in your champion the Game didn't load on your screen , that is most likely the issue !
For further assistance you can contact me on Discord @hiedeki
I'd like to tell me how it went :D

**Comment by Aerondightt2** [comment]
Can i show on discord to you ? @ARTIRL

**Comment by ARTIRL** [comment]
Check the new modified images folder with enhanced quality , it might help out!
Make sure to report the issue if it persists !
