### ISSUE TITLE
Request for Source Code and Potential Improvements

### ISSUE THREAD

**Issue by Blagabo** [ARTIRL/LevelingBOT_LOL#5]
Hi ARTIRL,

First of all, thank you for creating LevelingBOT_LOL—it’s an amazing tool! I’m currently using the bot, and it’s working great. I just had to make a small adjustment to the HUD size so it could correctly detect when it’s in-game.

I was wondering if you’d be willing to share the source code. I’d love to take a look and see if I can make some improvements to enhance its functionality. If I succeed, I’d be more than happy to share the updated version with you and the community.

Thanks again for your work, and I hope to hear from you soon!

**Comment by ARTIRL** [comment]
Greetings Blagabo, 

Thank you first for pointing out the fact of adjusting the HUD,which i forgot to mention in the readme file.

Also,
Ill be posting the source code probably soon (after making some new adjustments) to get a community working on the bot for more efficiency and performance.

Thank you for reaching me out and for your feedback.
