### ISSUE TITLE
Is the bot currently working?

### ISSUE THREAD

**Issue by 1Frc** [ARTIRL/LevelingBOT_LOL#6]
Hi, I wanted to know if the bot is working without a ban rate on Windows? Thank you very much.

**Comment by ARTIRL** [comment]
Yes the bot is currently working , I tried it with almost 5 accounts and i got a good feedback about it with 0% Ban Rate . 
Make sure to read the Readme file for system , settings requirements so the bot works efficiently

**Comment by 1Frc** [comment]
Can the bot be run on a virtual machine?
